### ISSUE TITLE
Consider convert lists into Components [1 effort - 1 value]

### ISSUE THREAD

**Issue by nickspiel** [fionajessica23/rea_challenge#1]
The 2 lists (results and saved `ul`) could be a component to eliminate repetition:
https://github.com/fionajessica23/rea_challenge/blob/422f8e48921747459a9337e4f545a3f87298b205/app/components/App.js#L36

**Comment by fionajessica23** [comment]
Created PropertyPanel Component that contain the list of PropertyCard
