### ISSUE TITLE
Consider adding a custom title meta tag to the page [1 effort - 2 value]

### ISSUE THREAD

**Issue by nickspiel** [fionajessica23/rea_challenge#10]
https://github.com/fionajessica23/rea_challenge/blob/422f8e48921747459a9337e4f545a3f87298b205/app/index.html#L7

**Comment by fionajessica23** [comment]
https://github.com/fionajessica23/rea_challenge/blob/d657cc454376870d03e18ed6348177b7451a3928/app/index.html#L7
