### ISSUE TITLE
Consider adding a main heading to the app [1 effort - 2 value]

### ISSUE THREAD

**Issue by nickspiel** [fionajessica23/rea_challenge#11]
https://github.com/fionajessica23/rea_challenge/blob/422f8e48921747459a9337e4f545a3f87298b205/app/components/App.js#L34

**Comment by fionajessica23** [comment]
Added `h1` "For Sale"

**Comment by fionajessica23** [comment]
https://github.com/fionajessica23/rea_challenge/blob/master/app/components/App.js#L34
