### ISSUE TITLE
Consider using css variables [2 effort - 3 value]

### ISSUE THREAD

**Issue by nickspiel** [fionajessica23/rea_challenge#7]
Consider using css variables for common layout dimensions, colors etc.

https://github.com/fionajessica23/rea_challenge/blob/422f8e48921747459a9337e4f545a3f87298b205/app/components/PropertyCard.scss#L16

**Comment by fionajessica23** [comment]
Created `style-variables.scss` file as a shared css variables

**Comment by nickspiel** [comment]
Niiiice!
