### ISSUE TITLE
Consider adding alt text to images [1 effort - 4 value]

### ISSUE THREAD

**Issue by nickspiel** [fionajessica23/rea_challenge#9]
https://github.com/fionajessica23/rea_challenge/blob/422f8e48921747459a9337e4f545a3f87298b205/app/components/PropertyCard.js#L15

**Comment by fionajessica23** [comment]
https://github.com/fionajessica23/rea_challenge/blob/d657cc454376870d03e18ed6348177b7451a3928/app/components/PropertyCard.js#L15

https://github.com/fionajessica23/rea_challenge/blob/d657cc454376870d03e18ed6348177b7451a3928/app/components/PropertyCard.js#L19
